name: Manual deployment to staging

on: workflow_dispatch

jobs:
  build_and_deploy:
    name: Build and deploy to staging

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Branch name
        run: echo Running on branch ${GITHUB_REF#refs/*/}

      - name: Deploy application
        uses: skore-io/git-actions/k8s@main
        with:
          ecr_repository: boilerplate
          k8s_credential: ${{ secrets.K8S_EKS_AMBIENTE_DEV }}
          service_base_url: boilerplate.learningrocks.info
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_KEY_ID_DEV }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_DEV }}
          tls_secret_name: boilerplate-tls
          k8s_replicas: 1
          subnets: subnet-xxx, subnet-yyy
          certificate_arn: arn:aws:acm:us-east-1:xxx
          limit_cpu: ${{ vars.K8S_DEV_LIMIT_CPU }}
          limit_memory: ${{ vars.K8S_DEV_LIMIT_MEMORY }}
          request_cpu: ${{ vars.K8S_DEV_REQUEST_CPU }}
          request_memory: ${{ vars.K8S_DEV_REQUEST_MEMORY }}
